# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# source 'https://github.com/multinetinventiv/MultipayPodSpecs.git'

target 'FrameworkTest' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
	# To use pod from Cocoapods
	# pod 'Multipay'

	# To use specific version
  # pod 'Multipay', '~> 1.0.24'

	# To use directly from repo
	# pod 'Multipay', :git => 'https://github.com/multinetinventiv/MultiPay-iOS-Sdk.git'

	# To use in development mode
	pod 'Multipay', :path => '../'

	pod 'IQKeyboardManagerSwift'


  target 'FrameworkTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "Multipay"
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end
